### ISSUE TITLE
potential error in calculating the drift angle?

### ISSUE THREAD

**Issue by jangroter** [ramondalmau/atcenv#3]
When plotting the histogram of the drift angle as provided by the function in the definitions.py file, I noticed a weird discrepancy where negative angles are under represented when compared with positive angles. As angles are radial and should therefore be continuous when going from +pi to -pi this jump should not exist (see figure)

![fbbb190d-dae4-49d8-a6d4-5aedab1026fe](https://user-images.githubusercontent.com/47716241/155964655-d7038aeb-da21-4311-9c55-efc465cdebfb.jpg)

I changed the drift angle calculation to the following code:

    def drift(self) -> float:
        """
        Drift angle (difference between track and bearing) to the target
        :return:
        """
        drift = self.bearing - self.track

        if drift > math.pi:
            return -(u.circle - drift)
        elif drift < -math.pi:
            return (u.circle + drift)
        else:
            return drift

This results in the following distributions of drift angles, which is more uniform and in line with my expectations;

![99c38ed3-471e-4150-9dcb-031e65d29969](https://user-images.githubusercontent.com/47716241/155964849-6ddc1675-8072-48fc-8284-8e0d497a7d3f.jpg)

I am not sure if the drift angle as implemented originally was intentionally setup to provide the drift as it does, but I have found that this way of calculating the drift is more reliable and contains more information for the agent.

Kind regards,
Jan

**Comment by ramondalmau** [comment]
Good morning Jan

You are right. The current implementation of the "drift" was copy-pasted from an old version.
My apologies. 

Note, however, that the distribution of drifts depends on the policy learnt by your agents, and therefore may not look always uniform (unless you are at the early stages of training with a lot of entropy)
 
I am going to update the current repo now

Best regards
Ramon

**Comment by jangroter** [comment]
Yes that makes sense, this histogram was indeed made under a random actor with high entropy. I am aware of the fact that the drift is not necessarily uniform, I actually hope that it become less uniform over time ;)

Thanks for the quick response!

**Comment by ramondalmau** [comment]
Amazing! Thanks to you, Jan. And good luck!
